server:
  port: 8081

spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret:
    access: 9ebef73f51e99ddc77a58f72be6f123a52faff38f47149ce91a061e0600b2f15
    refresh: 3a1f1cfffa888cc706918a1a19b9310c41dcbd36cdcdd89ee6bc11e2c5eb3ace