server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://51.250.26.59:5432/coffee_acc_db
    username: secUREusER
    password: StrongEnoughPassword)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1

  eureka:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/